package org.hkprog.xai.netbeans.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeListener;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import javax.swing.AbstractAction;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.border.AbstractBorder;
import org.hkprog.xai.netbeans.core.AgentEngine;
import org.hkprog.xai.netbeans.core.Mode;
import org.hkprog.xai.netbeans.settings.XaiSettings;
import org.hkprog.xai.netbeans.tools.FileChange;
import org.hkprog.xai.netbeans.tools.ToolContext;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.RequestProcessor;

/**
 * A single chat session: mode selector, transcript and prompt input. Multiple
 * instances run independently inside the assistant window, which is what powers
 * the "multitask" experience.
 * <p>
 * Layout lives in {@code SessionPanel.form} so this class opens in the NetBeans
 * GUI builder. Theme colors and behavior stay in hand-written code.
 */
public final class SessionPanel extends JPanel {

	private static final RequestProcessor RP = new RequestProcessor("xAI-Assistant", 8, true);

	private static final Color ACCENT = Theme.ACCENT;
	private static final Color MUTED = Theme.MUTED;

	private final Theme theme = Theme.current();

	private AgentEngine engine;
	private RequestProcessor.Task currentTask;
	/** Approval dialog currently open, so Stop can dismiss it. */
	private volatile NotifyDescriptor pendingApproval;

	public SessionPanel(Mode initialMode) {
		initComponents();
		applyTheme();
		modeBox.setSelectedItem(initialMode);
		engine = new AgentEngine(initialMode);
		wireActions();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        transcriptScroll = new javax.swing.JScrollPane();
        transcript = new org.hkprog.xai.netbeans.ui.Transcript();
        bottom = new javax.swing.JPanel();
        inputScroll = new javax.swing.JScrollPane();
        input = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        controls = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        modeLabel = new javax.swing.JLabel();
        modeBox = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 8));

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleLabel.setText("XAI Coding");
        header.add(titleLabel);

        add(header, java.awt.BorderLayout.NORTH);

        transcriptScroll.setViewportView(transcript);

        add(transcriptScroll, java.awt.BorderLayout.CENTER);

        bottom.setLayout(new java.awt.BorderLayout(0, 8));

        input.setColumns(40);
        input.setLineWrap(true);
        input.setRows(3);
        input.setWrapStyleWord(true);
        inputScroll.setViewportView(input);

        bottom.add(inputScroll, java.awt.BorderLayout.CENTER);

        sendButton.setText("↑");
        sendButton.setToolTipText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        bottom.add(sendButton, java.awt.BorderLayout.EAST);

        controls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 6, 0));

        statusLabel.setText(" ");
        controls.add(statusLabel);

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        controls.add(stopButton);

        modeLabel.setText("Mode:");
        controls.add(modeLabel);

        controls.add(modeBox);

        bottom.add(controls, java.awt.BorderLayout.SOUTH);

        add(bottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        stop();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        send();
    }//GEN-LAST:event_sendButtonActionPerformed

	private void applyTheme() {
		setBackground(theme.background);
		header.setBackground(theme.background);
		header.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, theme.border));
		titleLabel.setForeground(ACCENT);
		transcriptScroll.setBorder(BorderFactory.createEmptyBorder());
		transcriptScroll.getViewport().setBackground(theme.background);
		input.setFont(input.getFont().deriveFont(13f));
		input.setBorder(BorderFactory.createEmptyBorder(8, 12, 8, 12));
		inputScroll.setPreferredSize(new Dimension(100, 74));
		inputScroll.setBorder(new RoundedBorder(theme.inputBoxBorder, 14));
		inputScroll.getViewport().setBackground(theme.background);
		bottom.setBackground(theme.background);
		bottom.setBorder(BorderFactory.createEmptyBorder(10, 14, 12, 14));
		controls.setOpaque(false);
		modeLabel.setForeground(theme.subtle);
		statusLabel.setForeground(MUTED);
		stopButton.setVisible(false);
		for (Mode mode : Mode.values()) {
			modeBox.addItem(mode);
		}
	}

	private void wireActions() {
		modeBox.addActionListener(e -> {
			Mode selected = (Mode) modeBox.getSelectedItem();
			if (selected != null && (engine == null || engine.mode() != selected)) {
				engine = new AgentEngine(selected);
				transcript.appendInfo("Switched to " + selected.displayName()
						+ " mode (new conversation).");
			}
		});

		KeyStroke ctrlEnter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, InputEvent.CTRL_DOWN_MASK);
		input.getInputMap(JComponent.WHEN_FOCUSED).put(ctrlEnter, "send");
		input.getActionMap().put("send", new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				send();
			}
		});
	}

	Mode currentMode() {
		Mode m = (Mode) modeBox.getSelectedItem();
		return m == null ? Mode.AGENT : m;
	}

	private void send() {
		final String text = input.getText().trim();
		if (text.isEmpty() || currentTask != null) {
			return;
		}
		input.setText("");
		transcript.appendUser(text);
		setRunning(true);

		final AgentEngine activeEngine = engine;
		currentTask = RP.post(() -> {
			try {
				activeEngine.runUserTurn(text, approvalGate(), uiListener());
			} finally {
				EventQueue.invokeLater(() -> {
					currentTask = null;
					setRunning(false);
				});
			}
		});
	}

	private void stop() {
		if (engine != null) {
			engine.cancel();
		}
		statusLabel.setText("Stopping...");
		NotifyDescriptor pending = pendingApproval;
		if (pending != null) {
			// Non-modal notifyLater watches this and closes the dialog.
			pending.setValue(NotifyDescriptor.NO_OPTION);
		}
	}

	private void setRunning(boolean running) {
		sendButton.setEnabled(!running);
		stopButton.setVisible(running);
		modeBox.setEnabled(!running);
		statusLabel.setText(running ? "Working..." : " ");
	}

	private ToolContext.ApprovalGate approvalGate() {
		return (title, detail) -> {
			if (!XaiSettings.isRequireApproval()) {
				return true;
			}
			if (engine != null && engine.isCancelled()) {
				return false;
			}
			final boolean[] approved = {false};
			final CountDownLatch done = new CountDownLatch(1);
			EventQueue.invokeLater(() -> {
				if (engine != null && engine.isCancelled()) {
					done.countDown();
					return;
				}
				NotifyDescriptor d = new NotifyDescriptor.Confirmation(
						detail, title, NotifyDescriptor.YES_NO_OPTION);
				pendingApproval = d;
				PropertyChangeListener closed = evt -> {
					if (!NotifyDescriptor.PROP_VALUE.equals(evt.getPropertyName())) {
						return;
					}
					Object value = evt.getNewValue();
					if (value == null || value == NotifyDescriptor.CLOSED_OPTION
							|| value instanceof Integer && (Integer) value == -1) {
						return;
					}
					approved[0] = value == NotifyDescriptor.YES_OPTION
							&& (engine == null || !engine.isCancelled());
					pendingApproval = null;
					done.countDown();
				};
				d.addPropertyChangeListener(closed);
				// Non-modal so the Stop button stays clickable and can setValue(NO).
				DialogDisplayer.getDefault().notifyLater(d);
			});
			try {
				while (!done.await(250, TimeUnit.MILLISECONDS)) {
					if (engine != null && engine.isCancelled()) {
						NotifyDescriptor pending = pendingApproval;
						if (pending != null) {
							EventQueue.invokeLater(() -> pending.setValue(NotifyDescriptor.NO_OPTION));
						}
					}
				}
			} catch (InterruptedException ex) {
				Thread.currentThread().interrupt();
				return false;
			}
			return approved[0];
		};
	}

	private AgentEngine.Listener uiListener() {
		return new AgentEngine.Listener() {
			@Override
			public void onAssistantText(String text) {
				EventQueue.invokeLater(() -> transcript.appendAssistant(text));
			}

			@Override
			public void onToolCall(String name, String argumentsPreview) {
				EventQueue.invokeLater(() -> transcript.appendToolActivity(name + " " + argumentsPreview));
			}

			@Override
			public void onToolResult(String name, String resultPreview) {
				EventQueue.invokeLater(() -> transcript.appendToolActivity(name + " -> " + resultPreview));
			}

			@Override
			public void onActivity(String line) {
				EventQueue.invokeLater(() -> transcript.appendToolActivity(line));
			}

			@Override
			public void onError(String message) {
				EventQueue.invokeLater(() -> transcript.appendError(message));
			}

			@Override
			public void onComplete(List<FileChange> changes) {
				EventQueue.invokeLater(() -> transcript.appendFileChanges(changes));
			}
		};
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottom;
    private javax.swing.JPanel controls;
    private javax.swing.JPanel header;
    private javax.swing.JTextArea input;
    private javax.swing.JScrollPane inputScroll;
    private javax.swing.JComboBox<org.hkprog.xai.netbeans.core.Mode> modeBox;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel titleLabel;
    private org.hkprog.xai.netbeans.ui.Transcript transcript;
    private javax.swing.JScrollPane transcriptScroll;
    // End of variables declaration//GEN-END:variables

	/** Text area that paints a muted placeholder hint while empty and unfocused. */
	private static final class PlaceholderTextArea extends JTextArea {

		private final String hint;

		PlaceholderTextArea(String hint, int rows, int cols, Color background) {
			super(rows, cols);
			this.hint = hint;
			setBackground(background);
		}

		@Override
		protected void paintComponent(Graphics g) {
			super.paintComponent(g);
			if (getText().isEmpty() && !isFocusOwner()) {
				Graphics2D g2 = (Graphics2D) g.create();
				g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
						RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
				g2.setColor(MUTED);
				g2.setFont(getFont());
				java.awt.Insets in = getInsets();
				g2.drawString(hint, in.left, in.top + g2.getFontMetrics().getAscent());
				g2.dispose();
			}
		}
	}

	/** Small circular accent button used as the send control. */
	private static final class RoundButton extends JButton {

		RoundButton(String label) {
			super(label);
			setContentAreaFilled(false);
			setFocusPainted(false);
			setBorderPainted(false);
			setForeground(Color.white);
			setFont(getFont().deriveFont(Font.BOLD, 15f));
			setPreferredSize(new Dimension(34, 34));
			setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
		}

		@Override
		protected void paintComponent(Graphics g) {
			Graphics2D g2 = (Graphics2D) g.create();
			g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
			Color fill = isEnabled() ? (getModel().isArmed() ? ACCENT.darker() : ACCENT) : MUTED;
			g2.setColor(fill);
			int d = Math.min(getWidth(), getHeight());
			int x = (getWidth() - d) / 2;
			int y = (getHeight() - d) / 2;
			g2.fillOval(x, y, d - 1, d - 1);
			g2.dispose();
			super.paintComponent(g);
		}
	}

	/** Rounded line border for the prompt input. */
	private static final class RoundedBorder extends AbstractBorder {

		private final Color color;
		private final int radius;

		RoundedBorder(Color color, int radius) {
			this.color = color;
			this.radius = radius;
		}

		@Override
		public void paintBorder(java.awt.Component c, Graphics g, int x, int y, int w, int h) {
			Graphics2D g2 = (Graphics2D) g.create();
			g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
			g2.setColor(color);
			g2.drawRoundRect(x, y, w - 1, h - 1, radius, radius);
			g2.dispose();
		}

		@Override
		public java.awt.Insets getBorderInsets(java.awt.Component c) {
			return new java.awt.Insets(4, 4, 4, 4);
		}

		@Override
		public java.awt.Insets getBorderInsets(java.awt.Component c, java.awt.Insets insets) {
			insets.set(4, 4, 4, 4);
			return insets;
		}
	}
}
