package org.hkprog.xai.netbeans.ui;

import org.hkprog.xai.netbeans.core.Mode;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * The xAI assistant tool window. Hosts one or more {@link SessionPanel} tabs so
 * several Ask/Agent/Plan/Debug conversations can run in parallel (multitask).
 */
@TopComponent.Description(
        preferredID = "XaiAssistantTopComponent",
        iconBase = "org/hkprog/xai/netbeans/ui/icon.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "rightSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "org.hkprog.xai.netbeans.ui.XaiAssistantTopComponent")
@ActionReferences({
    @ActionReference(path = "Menu/Window", position = 333),
    @ActionReference(path = "Toolbars/Window", position = 333)
})
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_XaiAssistantAction",
        preferredID = "XaiAssistantTopComponent")
@Messages({
    "CTL_XaiAssistantAction=xAI Assistant",
    "CTL_XaiAssistantTopComponent=xAI Assistant",
    "HINT_XaiAssistantTopComponent=Chat with Grok to ask, plan, debug and edit your project"
})
public final class XaiAssistantTopComponent extends TopComponent {

    private int sessionCounter = 0;

    public XaiAssistantTopComponent() {
        initComponents();
        setName(Bundle.CTL_XaiAssistantTopComponent());
        setToolTipText(Bundle.HINT_XaiAssistantTopComponent());
        addSession(Mode.AGENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        newChat = new javax.swing.JButton();
        close = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        toolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 2));

        newChat.setText("New chat");
        newChat.setToolTipText("Open a new parallel session (multitask)");
        newChat.addActionListener(this::newChatActionPerformed);
        toolbar.add(newChat);

        close.setText("Close Tab");
        close.addActionListener(this::closeActionPerformed);
        toolbar.add(close);

        add(toolbar, java.awt.BorderLayout.NORTH);
        add(tabs, java.awt.BorderLayout.CENTER);
    }//GEN-END:initComponents

    private void newChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newChatActionPerformed
        addSession(Mode.AGENT);
    }//GEN-LAST:event_newChatActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        closeCurrent();
    }//GEN-LAST:event_closeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton newChat;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables

    private void addSession(Mode mode) {
        SessionPanel panel = new SessionPanel(mode);
        sessionCounter++;
        tabs.addTab(mode.displayName() + " " + sessionCounter, panel);
        tabs.setSelectedComponent(panel);
    }

    private void closeCurrent() {
        int idx = tabs.getSelectedIndex();
        if (idx >= 0 && tabs.getTabCount() > 1) {
            tabs.removeTabAt(idx);
        }
    }

    @Override
    public void componentOpened() {
        // no-op
    }

    @Override
    public void componentClosed() {
        // no-op
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        // nothing persisted beyond version
    }
}
