"""
A Manim tutorial that walks through the architecture of the `xai-netbeans`
module, following ARCHITECTURE.md, with an English voiceover (gTTS).

Render with (from the `video/` folder, network required for gTTS):

    .venv/bin/manim -qh architecture_tutorial.py ArchitectureTutorial

Narration is generated by gTTS and cached under media/voiceovers, so the audio
is only synthesized once per line. The whole talk is one Scene so it renders to
a single MP4; each chapter is a helper method called in order from construct().
"""

from manim import (
    VGroup,
    Text,
    RoundedRectangle,
    Line,
    DashedLine,
    Arrow,
    Table,
    Dot,
    Write,
    FadeIn,
    FadeOut,
    Create,
    GrowArrow,
    Indicate,
    LaggedStart,
    UP,
    DOWN,
    LEFT,
    RIGHT,
    ORIGIN,
)
from manim_voiceover import VoiceoverScene
from manim_voiceover.services.gtts import GTTSService

# ---------------------------------------------------------------------------
# Palette (xAI-ish: near-black canvas, bright accents)
# ---------------------------------------------------------------------------
BG = "#0b0e14"
FG = "#e6e6e6"
MUTED = "#8a93a3"
ACCENT = "#5ec8ff"   # blue   - UI / structure
GREEN = "#52d273"    # green  - read-only / safe
ORANGE = "#ffb454"   # orange - core / loop
PINK = "#ff7eb6"     # pink   - api / network
PURPLE = "#c792ea"   # purple - tools / settings
RED = "#ff5f6e"      # red    - mutating / danger


class ArchitectureTutorial(VoiceoverScene):
    def construct(self):
        self.camera.background_color = BG
        self.set_speech_service(GTTSService(lang="en", tld="com"))

        self.intro()
        self.what_is_it()
        self.component_map()
        self.packages_table()
        self.modes_table()
        self.tools_table()
        self.agent_loop()
        self.sequence_diagram()
        self.threading()
        self.limitations()
        self.outro()

    # ------------------------------------------------------------------ utils
    def chapter(self, number, title, narration, color=ACCENT):
        """A full-screen chapter card, narrated while it appears."""
        num = Text(f"{number:02d}", font="Menlo", color=color, weight="BOLD").scale(2.2)
        line = Line(LEFT, RIGHT, color=color).set_width(5).next_to(num, DOWN, buff=0.4)
        ttl = Text(title, color=FG, weight="BOLD").scale(0.9).next_to(line, DOWN, buff=0.4)
        grp = VGroup(num, line, ttl).move_to(ORIGIN)
        with self.voiceover(text=narration):
            self.play(FadeIn(num, shift=UP * 0.3), Create(line))
            self.play(Write(ttl))
        self.play(FadeOut(grp))

    def box(self, label, color, w=2.6, h=0.9, font_scale=0.36, sub=None):
        rect = RoundedRectangle(
            corner_radius=0.12, width=w, height=h,
            stroke_color=color, stroke_width=2.5, fill_color=color, fill_opacity=0.12,
        )
        txt = Text(label, color=FG, weight="BOLD").scale(font_scale)
        if sub:
            sub_t = Text(sub, color=MUTED).scale(font_scale * 0.72)
            inner = VGroup(txt, sub_t).arrange(DOWN, buff=0.08)
        else:
            inner = txt
        inner.move_to(rect.get_center())
        return VGroup(rect, inner)

    # ------------------------------------------------------------------ scenes
    def intro(self):
        title = Text("xAI NetBeans", color=FG, weight="BOLD").scale(1.5)
        subtitle = Text(
            "An agentic Grok assistant inside the NetBeans IDE",
            color=ACCENT,
        ).scale(0.5)
        subtitle.next_to(title, DOWN, buff=0.35)
        tag = Text("Architecture, end to end", color=MUTED, slant="ITALIC").scale(0.42)
        tag.next_to(subtitle, DOWN, buff=0.6)

        with self.voiceover(text=(
            "Welcome. This is xAI NetBeans, an agentic coding assistant powered by "
            "xAI's Grok model, embedded directly inside the Apache NetBeans I-D-E. "
            "In the next few minutes, we'll walk through its architecture, end to end."
        )):
            self.play(Write(title))
            self.play(FadeIn(subtitle, shift=UP * 0.2))
            self.play(FadeIn(tag))
        self.play(FadeOut(VGroup(title, subtitle, tag)))

    def what_is_it(self):
        self.chapter(1, "What this module is", "First, what exactly is this module?")

        heading = Text("A NetBeans Platform module (.nbm)", color=FG, weight="BOLD").scale(0.6)
        heading.to_edge(UP, buff=0.9)

        bullets = [
            ("Embeds an agentic coding assistant powered by xAI Grok", ACCENT),
            ("Adds a \u201cxAI Assistant\u201d tool window \u2014 you chat with Grok", ACCENT),
            ("Grok can read, search, and edit your project files", GREEN),
            ("Driven by an OpenAI-compatible function-calling loop", ORANGE),
        ]
        rows = VGroup()
        for text, c in bullets:
            dot = Dot(color=c, radius=0.06)
            t = Text(text, color=FG).scale(0.46)
            rows.add(VGroup(dot, t).arrange(RIGHT, buff=0.25))
        rows.arrange(DOWN, aligned_edge=LEFT, buff=0.4).next_to(heading, DOWN, buff=0.7)

        facts = Text(
            "Java 17  \u2022  NetBeans RELEASE240  \u2022  JDK HttpClient  \u2022  Gson  \u2022  commonmark",
            color=MUTED,
        ).scale(0.38).to_edge(DOWN, buff=0.6)

        with self.voiceover(text=(
            "xAI NetBeans is a NetBeans Platform module. It adds a xAI Assistant tool "
            "window where you chat with Grok. Grok can read your project, search it, "
            "and, in agent modes, create and edit files. Everything flows through an "
            "OpenAI-compatible function-calling loop."
        )):
            self.play(Write(heading))
            self.play(LaggedStart(*[FadeIn(r, shift=RIGHT * 0.3) for r in rows], lag_ratio=0.4))

        with self.voiceover(text=(
            "Under the hood, it's Java 17, built against NetBeans release 240, using "
            "the J-D-K's built-in HttpClient, Gson for J-SON, and commonmark for "
            "rendering the transcript."
        )):
            self.play(FadeIn(facts))

        self.play(FadeOut(VGroup(heading, rows, facts)))

    def component_map(self):
        self.chapter(2, "High-level component map",
                     "Let's see how the pieces fit together.", ORANGE)

        top = self.box("XaiAssistantTopComponent", ACCENT, w=4.6, sub="the tool window \u2022 N tabs")
        session = self.box("SessionPanel", ACCENT, w=4.0, sub="one chat session per tab")
        transcript = self.box("Transcript", ACCENT, w=3.0, sub="HTML conversation", h=0.85, font_scale=0.32)
        engine = self.box("AgentEngine", ORANGE, w=3.4, sub="history + agent loop", h=0.85, font_scale=0.32)
        settings = self.box("XaiSettings", GREEN, w=2.8, sub="runtime config", h=0.85, font_scale=0.32)

        top.to_edge(UP, buff=0.8)
        session.next_to(top, DOWN, buff=0.7)
        children = VGroup(transcript, engine, settings).arrange(RIGHT, buff=0.5)
        children.next_to(session, DOWN, buff=0.9)

        def connect(a, b, color=MUTED):
            return Line(a.get_bottom(), b.get_top(), color=color, stroke_width=2)

        top_arrow = Arrow(top.get_bottom(), session.get_top(), color=MUTED, buff=0.05)
        lines = VGroup(
            connect(session, transcript),
            connect(session, engine),
            connect(session, settings),
        )

        with self.voiceover(text=(
            "At the top is the Xai Assistant Top Component, the tool window that hosts "
            "multiple tabs. Each tab is a Session Panel, one independent chat session. "
            "A session owns a Transcript for the conversation view, an Agent Engine "
            "that drives the agent, and it reads the settings at runtime."
        )):
            self.play(FadeIn(top, shift=DOWN * 0.2))
            self.play(GrowArrow(top_arrow))
            self.play(FadeIn(session, shift=DOWN * 0.2))
            self.play(Create(lines))
            self.play(LaggedStart(*[FadeIn(c, shift=UP * 0.2) for c in children], lag_ratio=0.3))

        internals = VGroup(
            self.box("XaiClient \u2192 Grok API", PINK, w=3.4, h=0.6, font_scale=0.3),
            self.box("ToolRegistry (5 tools)", PURPLE, w=3.4, h=0.6, font_scale=0.3),
            self.box("SystemPrompts.forMode()", ORANGE, w=3.4, h=0.6, font_scale=0.3),
        ).arrange(DOWN, buff=0.2)
        internals.next_to(engine, DOWN, buff=0.6).shift(RIGHT * 0.2)
        brace = Line(engine.get_bottom(), internals.get_top(), color=MUTED, stroke_width=2)

        with self.voiceover(text=(
            "The Agent Engine is the heart of the module. It holds the conversation "
            "history and coordinates three things: the Xai Client that talks to the "
            "Grok API, a Tool Registry of five callable tools, and the system prompt "
            "for the current mode."
        )):
            self.play(Create(brace), LaggedStart(*[FadeIn(i) for i in internals], lag_ratio=0.3))

        self.play(FadeOut(VGroup(top, top_arrow, session, children, lines, internals, brace)))

    def packages_table(self):
        self.chapter(3, "Five packages, five jobs",
                     "The code is organized into five packages.", PURPLE)

        data = [
            ["api", "HTTP transport + wire model (XaiClient, ChatMessage)"],
            ["core", "Mode, SystemPrompts, the AgentEngine loop"],
            ["settings", "XaiSettings (NbPreferences) + Options panel"],
            ["tools", "AgentTool impls, ToolRegistry, Workspace"],
            ["ui", "TopComponent, SessionPanel, Transcript"],
        ]
        table = Table(
            data,
            col_labels=[Text("package", weight="BOLD"), Text("responsibility", weight="BOLD")],
            include_outer_lines=False,
            line_config={"stroke_color": MUTED, "stroke_width": 1},
            element_to_mobject=lambda s: Text(s, color=FG),
        ).scale(0.42)
        table.get_col_labels().set_color(ACCENT)
        names_to_color = {"api": PINK, "core": ORANGE, "settings": GREEN, "tools": PURPLE, "ui": ACCENT}
        for i, (name, _) in enumerate(data):
            table.add_highlighted_cell((i + 2, 1), color=names_to_color[name], fill_opacity=0.10)
        table.move_to(ORIGIN).shift(DOWN * 0.2)

        with self.voiceover(text=(
            "The api package handles H-T-T-P transport and the wire data model. "
            "core holds the Mode enum, the system prompts, and the Agent Engine loop. "
            "settings stores configuration in NetBeans preferences and adds the "
            "Options panel. tools contains the tool implementations, the registry, "
            "and path resolution. And u-i is the tool window, the session panel, and "
            "the transcript."
        )):
            self.play(Create(table.get_horizontal_lines()), Create(table.get_vertical_lines()))
            self.play(Write(table.get_col_labels()))
            self.play(LaggedStart(*[FadeIn(table.get_rows()[i]) for i in range(1, len(data) + 1)], lag_ratio=0.3))

        self.play(FadeOut(table))

    def modes_table(self):
        self.chapter(4, "Modes decide what Grok may do",
                     "What Grok is allowed to do depends on the mode.", GREEN)

        data = [
            ["ASK", "no", "3 read-only", "answer + cite files/lines"],
            ["PLAN", "no", "3 read-only", "numbered change plan"],
            ["DEBUG", "no", "3 read-only", "hypothesis \u2192 root cause"],
            ["AGENT", "yes", "all 5", "full autonomy, prefers edit_file"],
            ["MULTITASK", "yes", "all 5", "AGENT across parallel tabs"],
        ]
        table = Table(
            data,
            col_labels=[
                Text("mode", weight="BOLD"),
                Text("mutates?", weight="BOLD"),
                Text("tools", weight="BOLD"),
                Text("intent", weight="BOLD"),
            ],
            include_outer_lines=False,
            line_config={"stroke_color": MUTED, "stroke_width": 1},
            element_to_mobject=lambda s: Text(s, color=FG),
        ).scale(0.4)
        table.get_col_labels().set_color(ACCENT)
        for i, row in enumerate(data):
            color = GREEN if row[1] == "no" else RED
            table.add_highlighted_cell((i + 2, 2), color=color, fill_opacity=0.18)
        table.move_to(ORIGIN).shift(DOWN * 0.2)

        note = Text(
            "Switching the mode builds a NEW engine \u2014 fresh prompt, empty history.",
            color=MUTED, slant="ITALIC",
        ).scale(0.38).to_edge(DOWN, buff=0.5)

        with self.voiceover(text=(
            "There are five modes. Ask, Plan, and Debug are read-only. They expose "
            "three safe tools and never modify files. Agent and Multitask are "
            "read-write. They expose all five tools and can edit your project, with "
            "Multitask running across parallel tabs."
        )):
            self.play(Create(table.get_horizontal_lines()), Create(table.get_vertical_lines()))
            self.play(Write(table.get_col_labels()))
            self.play(LaggedStart(*[FadeIn(table.get_rows()[i]) for i in range(1, len(data) + 1)], lag_ratio=0.25))

        with self.voiceover(text=(
            "One important detail: switching the mode builds a brand-new engine, with "
            "a fresh prompt and an empty history."
        )):
            self.play(FadeIn(note))

        self.play(FadeOut(VGroup(table, note)))

    def tools_table(self):
        self.chapter(5, "The five tools Grok can call",
                     "Now, the tools themselves.", PURPLE)

        data = [
            ["read_file", "no", "read a file (optional line range)"],
            ["list_dir", "no", "list a dir (skips .git, target, node_modules)"],
            ["search", "no", "regex search across files"],
            ["write_file", "yes", "create/overwrite a file \u2014 needs approval"],
            ["edit_file", "yes", "exact old\u2192new replacement \u2014 needs approval"],
        ]
        table = Table(
            data,
            col_labels=[
                Text("tool", weight="BOLD"),
                Text("mutating", weight="BOLD"),
                Text("what it does", weight="BOLD"),
            ],
            include_outer_lines=False,
            line_config={"stroke_color": MUTED, "stroke_width": 1},
            element_to_mobject=lambda s: Text(s, color=FG),
        ).scale(0.42)
        table.get_col_labels().set_color(ACCENT)
        for i, row in enumerate(data):
            color = GREEN if row[1] == "no" else RED
            table.add_highlighted_cell((i + 2, 1), color=color, fill_opacity=0.14)
        table.move_to(ORIGIN).shift(DOWN * 0.15)

        legend = VGroup(
            VGroup(Dot(color=GREEN, radius=0.07), Text("read-only", color=FG).scale(0.36)).arrange(RIGHT, buff=0.15),
            VGroup(Dot(color=RED, radius=0.07), Text("mutating (gated by approval)", color=FG).scale(0.36)).arrange(RIGHT, buff=0.15),
        ).arrange(RIGHT, buff=0.8).to_edge(DOWN, buff=0.5)

        with self.voiceover(text=(
            "Grok can call five tools. read file, list dir, and search are read-only; "
            "they inspect your project. write file and edit file are mutating. write "
            "file creates or overwrites a file, and edit file makes an exact string "
            "replacement. Both require your approval before they touch disk."
        )):
            self.play(Create(table.get_horizontal_lines()), Create(table.get_vertical_lines()))
            self.play(Write(table.get_col_labels()))
            self.play(LaggedStart(*[FadeIn(table.get_rows()[i]) for i in range(1, len(data) + 1)], lag_ratio=0.25))
            self.play(FadeIn(legend))

        self.play(FadeOut(VGroup(table, legend)))

    def agent_loop(self):
        self.chapter(6, "The agent loop",
                     "This brings us to the agent loop, the core of how a turn runs.", ORANGE)

        heading = Text("runUserTurn:  request \u2192 tool-call \u2192 tool-result", color=FG, weight="BOLD").scale(0.5)
        heading.to_edge(UP, buff=0.7)

        user = self.box("history += user(text)", FG, w=3.2, h=0.7, font_scale=0.3)
        call = self.box("XaiClient.complete\n(history, specs)", PINK, w=3.0, h=0.9, font_scale=0.3)
        check = self.box("tool_calls?", ORANGE, w=2.4, h=0.7, font_scale=0.32)
        run = self.box("dispatch:\napprove \u2192 run \u2192 refresh", PURPLE, w=3.4, h=0.9, font_scale=0.3)
        done = self.box("onComplete()\nfinal answer", GREEN, w=2.8, h=0.8, font_scale=0.3)

        user.move_to([-4.2, 1.4, 0])
        call.move_to([0, 1.4, 0])
        check.move_to([3.8, 1.4, 0])
        run.move_to([3.8, -1.4, 0])
        done.move_to([-1.0, -1.4, 0])

        a_uc = Arrow(user.get_right(), call.get_left(), color=MUTED, buff=0.1)
        a_cc = Arrow(call.get_right(), check.get_left(), color=MUTED, buff=0.1)
        a_yes = Arrow(check.get_bottom(), run.get_top(), color=ORANGE, buff=0.1)
        yes_lbl = Text("yes", color=ORANGE).scale(0.34).next_to(a_yes, RIGHT, buff=0.1)
        a_loop = Arrow(run.get_left(), call.get_bottom(), color=ORANGE, buff=0.15)
        loop_lbl = Text("history += toolResult", color=MUTED).scale(0.3).next_to(a_loop, DOWN, buff=0.05)
        a_no = Arrow(check.get_bottom() + LEFT * 0.4, done.get_right(), color=GREEN, buff=0.15)
        no_lbl = Text("no", color=GREEN).scale(0.34).next_to(a_no, UP, buff=0.05)
        cap = Text(
            "Repeats up to maxAgentIterations (default 25). Every call sends the ENTIRE history.",
            color=MUTED, slant="ITALIC",
        ).scale(0.36).to_edge(DOWN, buff=0.45)

        with self.voiceover(text=(
            "When you send a prompt, your message is appended to the history. The "
            "engine then calls the Grok API with the history and the tools allowed by "
            "your mode."
        )):
            self.play(Write(heading))
            self.play(FadeIn(user))
            self.play(GrowArrow(a_uc))
            self.play(FadeIn(call))
            self.play(GrowArrow(a_cc))
            self.play(FadeIn(check))

        with self.voiceover(text=(
            "If the response contains no tool calls, the turn is done, and you get the "
            "final answer."
        )):
            self.play(GrowArrow(a_no), FadeIn(no_lbl))
            self.play(FadeIn(done))

        with self.voiceover(text=(
            "But if Grok requests tool calls, the engine dispatches each one, checking "
            "approval, executing it, and refreshing the I-D-E. It appends the results "
            "to the history and calls the model again."
        )):
            self.play(GrowArrow(a_yes), FadeIn(yes_lbl))
            self.play(FadeIn(run))
            self.play(GrowArrow(a_loop), FadeIn(loop_lbl))

        with self.voiceover(text=(
            "This repeats until Grok stops asking for tools, up to a default of "
            "twenty-five iterations. Note that every single call sends the entire "
            "history."
        )):
            self.play(FadeIn(cap))
            self.play(Indicate(call, color=PINK), Indicate(run, color=PURPLE))

        self.play(FadeOut(VGroup(
            heading, user, call, check, run, done,
            a_uc, a_cc, a_yes, yes_lbl, a_loop, loop_lbl, a_no, no_lbl, cap,
        )))

    # ----------------------------------------------------- sequence diagram
    def _seq_msg(self, frm, to, label, color, y, dashed=False):
        """Build one message: an arrow between two lifelines, with a label.

        A self-message (frm == to) is drawn as a small loop hanging off the
        lane; a cross-lane message is a straight (optionally dashed) arrow.
        """
        x1 = self._lane_x[frm]
        if frm == to:
            x = x1
            l1 = Line([x, y + 0.10, 0], [x + 0.5, y + 0.10, 0], color=color, stroke_width=2.5)
            l2 = Line([x + 0.5, y + 0.10, 0], [x + 0.5, y - 0.10, 0], color=color, stroke_width=2.5)
            ret = Arrow(
                [x + 0.5, y - 0.10, 0], [x, y - 0.10, 0], color=color, buff=0,
                stroke_width=2.5, tip_length=0.14, max_tip_length_to_length_ratio=0.4,
            )
            lbl = Text(label, color=color).scale(0.24).next_to(l2, RIGHT, buff=0.12)
            return VGroup(l1, l2, ret, lbl)

        x2 = self._lane_x[to]
        start, end = [x1, y, 0], [x2, y, 0]
        if dashed:
            arr = DashedLine(start, end, color=color, stroke_width=2.5, dash_length=0.12)
            arr.add_tip(tip_length=0.18, tip_width=0.16)
        else:
            arr = Arrow(
                start, end, color=color, buff=0.04, stroke_width=2.5,
                tip_length=0.18, max_tip_length_to_length_ratio=0.05,
            )
        lbl = Text(label, color=color).scale(0.24).move_to([(x1 + x2) / 2, y + 0.17, 0])
        return VGroup(arr, lbl)

    def _seq_phase(self, label_text, narration, steps):
        """Animate one phase: swap the phase label, drop messages one by one
        down the lifelines while narrating, then clear them (lanes persist)."""
        new_lbl = Text(label_text, color=PINK, weight="BOLD").scale(0.36).move_to([0, 3.7, 0])
        built = []
        y = 2.05
        for frm, to, label, color, dashed in steps:
            built.append(self._seq_msg(frm, to, label, color, y, dashed))
            y -= 0.5

        msgs = VGroup()
        with self.voiceover(text=narration):
            if self._cur_phase is None:
                self.play(FadeIn(new_lbl))
            else:
                self.play(FadeOut(self._cur_phase), FadeIn(new_lbl))
            self._cur_phase = new_lbl
            for m in built:
                self.play(FadeIn(m, shift=DOWN * 0.1), run_time=0.55)
                msgs.add(m)
        self.play(FadeOut(msgs), run_time=0.5)

    def sequence_diagram(self):
        self.chapter(7, "End-to-end sequence",
                     "Now let's trace one full request, step by step, "
                     "across every participant.", PINK)

        lanes_def = [
            ("User", "User", FG),
            ("SP", "SessionPanel", ACCENT),
            ("TR", "Transcript", ACCENT),
            ("RP", "ReqProcessor", ORANGE),
            ("AE", "AgentEngine", ORANGE),
            ("XC", "XaiClient", PINK),
            ("API", "Grok API", PINK),
            ("REG", "Registry", PURPLE),
            ("T", "AgentTool", PURPLE),
            ("WS", "Workspace", PURPLE),
            ("NB", "NetBeans", GREEN),
        ]
        n = len(lanes_def)
        left, right = -6.4, 6.4
        xs = [left + (right - left) * i / (n - 1) for i in range(n)]
        top_y, bottom_y = 3.0, -3.5

        self._lane_x = {}
        self._cur_phase = None
        headers = VGroup()
        lifelines = VGroup()
        for (alias, full, color), x in zip(lanes_def, xs):
            head = self.box(alias, color, w=1.12, h=0.5, font_scale=0.3)
            head.move_to([x, top_y, 0])
            sub = Text(full, color=MUTED).scale(0.2).next_to(head, DOWN, buff=0.06)
            line = DashedLine(
                [x, top_y - 0.62, 0], [x, bottom_y, 0],
                color=color, stroke_width=1.2, dash_length=0.09,
            ).set_opacity(0.45)
            self._lane_x[alias] = x
            headers.add(VGroup(head, sub))
            lifelines.add(line)

        with self.voiceover(text=(
            "Here are the eleven participants, from you on the left to NetBeans "
            "on the right. Each vertical line is a lifeline; messages flow "
            "between them, top to bottom, as the turn runs."
        )):
            self.play(LaggedStart(*[FadeIn(h, shift=DOWN * 0.15) for h in headers], lag_ratio=0.12))
            self.play(Create(lifelines))

        self._seq_phase(
            "1 \u00b7 Submit the prompt",
            (
                "You type a prompt and hit Send. The Session Panel guards against "
                "empty or already-running input, echoes your text into the "
                "transcript, flips into the Working state, and posts the turn onto "
                "the background Request Processor, which invokes the Agent Engine's "
                "run-user-turn."
            ),
            [
                ("User", "SP", "prompt + Send", ACCENT, False),
                ("SP", "SP", "send() guards", ACCENT, False),
                ("SP", "TR", "appendUser(text)", ACCENT, False),
                ("SP", "SP", "setRunning \u00b7 Working\u2026", ACCENT, False),
                ("SP", "RP", "post(runUserTurn)", ORANGE, False),
                ("RP", "AE", "runUserTurn(text, gate)", ORANGE, False),
            ],
        )

        self._seq_phase(
            "2 \u00b7 Request \u2192 response",
            (
                "Inside the loop, the Agent Engine asks the Xai Client to complete "
                "the conversation. The client builds the J-SON body and posts it to "
                "the Grok API. The API returns a message, which becomes a "
                "ChatMessage flowing back to the engine. If it carries text, that's "
                "pushed to the Session Panel and rendered into the transcript."
            ),
            [
                ("AE", "XC", "complete(history, specs)", ORANGE, False),
                ("XC", "XC", "build JSON body", PINK, False),
                ("XC", "API", "POST /chat/completions", PINK, False),
                ("API", "XC", "choices[0].message", MUTED, True),
                ("XC", "AE", "ChatMessage assistant", MUTED, True),
                ("AE", "SP", "onAssistantText", MUTED, True),
                ("SP", "TR", "appendAssistant (md\u2192html)", ACCENT, False),
            ],
        )

        self._seq_phase(
            "3 \u00b7 Tool call",
            (
                "If the response asks for a tool, the engine looks it up in the "
                "registry, checks the mode's mutation policy, and executes the tool. "
                "For a mutating tool it first requests your approval, blocking until "
                "you decide. Then it resolves the path, reads or writes through java "
                "N-I-O, and asks NetBeans to refresh so the I-D-E sees the change."
            ),
            [
                ("AE", "REG", "get(name) + check", PURPLE, False),
                ("AE", "T", "execute(args, ctx)", PURPLE, False),
                ("T", "NB", "requestApproval", RED, False),
                ("NB", "T", "approved? (blocks)", RED, True),
                ("T", "WS", "resolve(path)", PURPLE, False),
                ("T", "T", "read / write", PURPLE, False),
                ("T", "WS", "refresh(file)", PURPLE, False),
                ("WS", "NB", "FileObject.refresh()", GREEN, False),
            ],
        )

        self._seq_phase(
            "4 \u00b7 Result, loop & done",
            (
                "The tool's result returns to the engine, is surfaced to the "
                "transcript, and appended to the history. The loop then repeats, "
                "calling the model again, until Grok stops asking for tools and "
                "signals completion. Finally, back on the U-I thread, the Session "
                "Panel restores its idle state."
            ),
            [
                ("T", "AE", "result string", MUTED, True),
                ("AE", "SP", "onToolResult(preview)", MUTED, True),
                ("SP", "TR", "appendToolActivity", ACCENT, False),
                ("AE", "AE", "history += toolResult \u21ba", ORANGE, False),
                ("AE", "SP", "onComplete()", GREEN, True),
                ("RP", "SP", "finally: setRunning(false)", ORANGE, False),
            ],
        )

        self.play(FadeOut(VGroup(headers, lifelines, self._cur_phase)))

    def threading(self):
        self.chapter(8, "Threading model", "A quick word on threading.", ACCENT)

        edt = self.box("EDT (Swing)", ACCENT, w=4.4, h=1.6, font_scale=0.42,
                       sub="all UI: input, transcript, approval dialogs")
        rp = self.box("RequestProcessor pool", ORANGE, w=4.4, h=1.6, font_scale=0.42,
                      sub="\u201cxAI-Assistant\u201d, 8 threads: runUserTurn, HTTP, tools")
        edt.move_to([-3.2, 0.3, 0])
        rp.move_to([3.2, 0.3, 0])

        a1 = Arrow(edt.get_right(), rp.get_left(), color=MUTED, buff=0.1).shift(UP * 0.3)
        l1 = Text("post(runUserTurn)", color=MUTED).scale(0.32).next_to(a1, UP, buff=0.05)
        a2 = Arrow(rp.get_left(), edt.get_right(), color=MUTED, buff=0.1).shift(DOWN * 0.3)
        l2 = Text("invokeLater(callbacks)", color=MUTED).scale(0.32).next_to(a2, DOWN, buff=0.05)

        bridge = Text(
            "Approval bridge: mutating tools block their thread on invokeAndWait\n"
            "while the EDT shows the Yes/No dialog.",
            color=PINK,
        ).scale(0.36).to_edge(DOWN, buff=0.6)

        with self.voiceover(text=(
            "All user-interface work happens on the Swing event dispatch thread: "
            "input, the transcript, and approval dialogs. The agent turn, the blocking "
            "H-T-T-P call, and tool execution run on a background Request Processor "
            "pool with eight threads, so up to eight tabs can work at once. Callbacks "
            "are marshalled back to the U-I thread."
        )):
            self.play(FadeIn(edt, shift=RIGHT * 0.2), FadeIn(rp, shift=LEFT * 0.2))
            self.play(GrowArrow(a1), FadeIn(l1))
            self.play(GrowArrow(a2), FadeIn(l2))

        with self.voiceover(text=(
            "When a mutating tool needs approval, it blocks its background thread and "
            "waits while the dialog is shown. That's the approval bridge."
        )):
            self.play(FadeIn(bridge))

        self.play(FadeOut(VGroup(edt, rp, a1, l1, a2, l2, bridge)))

    def limitations(self):
        self.chapter(9, "Design choices & limits",
                     "Finally, some deliberate design choices and limits.", RED)

        items = [
            ("Non-streaming \u2014 a turn blocks until the full response arrives", ORANGE),
            ("No editor integration \u2014 edits hit disk, then FileObject.refresh()", RED),
            ("No command execution \u2014 only the 5 filesystem tools", RED),
            ("Regex search, not the IDE index", PURPLE),
            ("No conversation persistence \u2014 closing the IDE discards history", MUTED),
            ("Mode switch resets the engine; approval blocks the agent thread", ACCENT),
        ]
        rows = VGroup()
        for text, c in items:
            dot = Dot(color=c, radius=0.06)
            t = Text(text, color=FG).scale(0.42)
            rows.add(VGroup(dot, t).arrange(RIGHT, buff=0.22))
        rows.arrange(DOWN, aligned_edge=LEFT, buff=0.38).move_to(ORIGIN)

        with self.voiceover(text=(
            "The client is non-streaming; a turn blocks until the full response "
            "arrives. There's no editor integration: edits go straight to disk and are "
            "surfaced with a file refresh. There's no command execution, only the five "
            "filesystem tools. Search uses regex over files rather than the I-D-E "
            "index. Conversations aren't persisted across restarts. And approval "
            "intentionally blocks the agent until you decide."
        )):
            self.play(LaggedStart(*[FadeIn(r, shift=RIGHT * 0.3) for r in rows], lag_ratio=0.3))

        self.play(FadeOut(rows))

    def outro(self):
        title = Text("That's the architecture.", color=FG, weight="BOLD").scale(1.0)
        sub = Text(
            "UI \u2192 AgentEngine \u2192 Grok \u2192 tools \u2192 your files",
            color=ACCENT,
        ).scale(0.5).next_to(title, DOWN, buff=0.4)
        ref = Text("See ARCHITECTURE.md for the full details", color=MUTED, slant="ITALIC").scale(0.4)
        ref.next_to(sub, DOWN, buff=0.6)

        with self.voiceover(text=(
            "And that's the architecture, end to end: from the U-I, through the Agent "
            "Engine, to Grok, to the tools, and finally to your files. For all the "
            "details, see the architecture markdown file. Thanks for watching."
        )):
            self.play(Write(title))
            self.play(FadeIn(sub, shift=UP * 0.2))
            self.play(FadeIn(ref))
        self.play(FadeOut(VGroup(title, sub, ref)))
